//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBoutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int idCommande { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string adresseLivraison { get; set; }
        public string detailLivraison { get; set; }
        public Nullable<System.DateTime> dateLivraison { get; set; }
    }
}
