//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBoutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facture
    {
        public int idfacture { get; set; }
        public Nullable<int> idCommande { get; set; }
        public Nullable<System.DateTime> dateFacture { get; set; }
        public Nullable<double> TVA { get; set; }
        public Nullable<int> remise { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> totalttc { get; set; }
    
        public virtual Commande Commande { get; set; }
    }
}
