//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBoutique.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public Nullable<int> idarticle { get; set; }
        public Nullable<int> idcommande { get; set; }
        public Nullable<decimal> qtecmde { get; set; }
        public int idlignecommande { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
